# Generated by Django 5.2.8 on 2026-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=200)),
                ('disease_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('image_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='affected_crops',
        ),
        migrations.AddField(
            model_name='disease',
            name='crop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='reference',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
